---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-request-limit
spec:
  containers:
  - name: cpu-request-limit
    image: vish/stress
    args:
    - -cpus
    - "2"
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.1"

---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-request-limit-2
spec:
  containers:
  - name: cpu-request-limit-2
    image: vish/stress
    args:
    - -cpus
    - "4"

---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-request-limit-3
spec:
  containers:
  - name: cpu-request-limit-3
    image: vish/stress
    args:
    - -cpus
    - "2"
    resources:
      limits:
        memory: "128M"
        cpu: "1"
      requests:
        memory: "128M"
        cpu: "1"

