---
apiVersion: v1
kind: Namespace
metadata:
  name: qos-example

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-guaranteed
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-burstable
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "100Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-bestfffort
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
