apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit
spec:
  containers:
  - name: memory-request-limit
    image: polinux/stress:1.0.4
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
