---
apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-2
  labels:
    name: memory-request-limit-2
spec:
  containers:
  - image: busybox:1.28
    command: ["/bin/sh"]
    args: ["-c", "while true; do tail /dev/zero; echo $?; sleep 10;done"]
    name: busybox
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"

---
apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-2-2
  labels:
    name: memory-request-limit-2-2
spec:
  containers:
  - image: busybox:1.28
    command: ["/bin/sh"]
    args: ["-c", "tail /dev/zero"]
    name: busybox
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
