apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-3
spec:
  containers:
  - name: memory-request-limit-3
    image: polinux/stress:1.0.4
    resources:
      requests:
        memory: "10000Mi"
      limits:
        memory: "10000Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
